# docker-compose up -d
version: '3'
services:
    bhp:
        container_name: bhp
        image: lkeme/bilihelper-personal:latest # my-app: x.x.x
        stdin_open: true # docker run -i 交互模式
        tty: true        # docker run -t 终端模式
        restart: on-failure:5 # 重启策略 / on-failure:5 重启次数5次 / always 一直重启 / unless-stopped 除非停止 / no 从不重启
        volumes:
            - /opt/bhp/profile/user:/app/profile/user  # /opt/bhp/profile/user替换为自己的路径
        network_mode: bridge # host
        ports:
            - "50001:50001" # 50001替换为自己的端口 user.ini->login_captcha->url
        environment:
            MIRRORS: 1 # 使用github镜像加速 docs/DOC.md#docker使用指南
            CAPTCHA: 1 # docs/CAPTCHA.md

