name: "BiliHelper-personal Docker Image Buildx Stable Github"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build BiliHelper-personal Docker Image Build Stable Github
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: lkeme/bilihelper-personal
          dockerFile: docker/Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          tag: latest
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}